name: 'DORA deployment frequency'
description: 'A GitHub Action to roughly calculate DORA deployment frequency'
author: developermetrics.org 
branding:
  icon: activity
  color: gray-dark
inputs:
  workflows: # required. string array of the name of the workflows to process
    description: the workflow name that is being scanned. Separate multiple workflows with commas
    required: true
  owner-repo: # optional, defaults to current owner/repo
    description: target org/repo or owner/repo to run the calculation on
    required: true
    default: "${{ github.repository }}"
  default-branch:  # optional, defaults to main
    description: branch that is deploying to production
    required: true
    default: 'main'
  number-of-days: # optional, defaults to 30
    description: number of days to scan
    required: true
    default: "30"
  pat-token: # optional, defaults to an empty string ("")
    description: GitHub PAT Token
    default: ""
  actions-token: # optional, defaults to an empty string ("")
    description: GitHub Actions Token, commonly passed in as a variable (secrets.GITHUB_TOKEN)
    default: ""
  app-id:
    description: 'application id of the registered GitHub app'
    default: ""
  app-install-id:
    description: 'id of the installed instance of the GitHub app'
    default: ""
  app-private-key:
    description: 'private key which has been generated for the installed instance of the GitHub app'
    default: ""
outputs:
  markdown-file:
    description: "The markdown that will be posted to the job summary, so that the markdown can saved and used other places (e.g.: README.md)"
    value: ${{ steps.deployment-frequency.outputs.markdown-file }}
runs:
  using: "composite"
  steps:
    - name: Setup GH CLI
      uses: sersoft-gmbh/setup-gh-cli-action@main
      with:
        version: stable
    - name: Run DORA deployment frequency
      id: deployment-frequency
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        result=$(bash ${{ github.action_path }}/src/deploymentfrequency.sh -o "${{ inputs.owner-repo }}" -w "${{ inputs.workflows }}" -b "${{ inputs.default-branch }}" -n "${{ inputs.number-of-days }}" -p "${{ inputs.pat-token }}" -a "${{ inputs.actions-token }}" -i "${{ inputs.app-id }}" -I "${{ inputs.app-install-id }}" -k "${{ inputs.app-private-key }}")
        filePath="dora-deployment-frequency-markdown.md"
        echo "$result" > $filePath
        echo "markdown-file=$filePath" >> $GITHUB_OUTPUT
        echo "$result" >> $GITHUB_STEP_SUMMARY
